// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// package llnl.visit.operators;

// import llnl.visit.AttributeSubject;
// import llnl.visit.CommunicationBuffer;
// import llnl.visit.Plugin;
import java.util.Vector;

// ****************************************************************************
// Class: DeferExpressionAttributes
//
// Purpose:
//    Attributes for the DeferExpression operator
//
// Notes:      Autogenerated by xml2java.
//
// Programmer: xml2java
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

public class DeferExpressionAttributes
{
    private static int DeferExpressionAttributes_numAdditionalAtts = 1;

    public DeferExpressionAttributes()
    {

        exprs = new Vector<String>();
    }

    public DeferExpressionAttributes(int nMoreFields)
    {

        exprs = new Vector<String>();
    }

    public DeferExpressionAttributes(DeferExpressionAttributes obj)
    {

        int i;

        exprs = new Vector<String>(obj.exprs.size());
        for(i = 0; i < obj.exprs.size(); ++i)
            exprs.addElement(new String((String)obj.exprs.elementAt(i)));


    }

    public int Offset()
    {
        return 0;
    }

    public int GetNumAdditionalAttributes()
    {
        return DeferExpressionAttributes_numAdditionalAtts;
    }

    public boolean equals(DeferExpressionAttributes obj)
    {
        int i;

        // Compare the elements in the exprs vector.
        boolean exprs_equal = (obj.exprs.size() == exprs.size());
        for(i = 0; (i < exprs.size()) && exprs_equal; ++i)
        {
            // Make references to String from Object.
            String exprs1 = (String)exprs.elementAt(i);
            String exprs2 = (String)obj.exprs.elementAt(i);
            exprs_equal = exprs1.equals(exprs2);
        }
        // Create the return value
        return (exprs_equal);
    }

    public String GetName() { return "DeferExpression"; }
    public String GetVersion() { return "1.0"; }

    // Property setting methods
    public void SetExprs(Vector<String> exprs_)
    {
        exprs = exprs_;
    }

    // Property getting methods
    public Vector<String> GetExprs() { return exprs; }

    public String toString(String indent)
    {
        String str = new String();
        return str;
    }


    // Attributes
    private Vector<String> exprs; // vector of String objects
}

